# Generated by Django 5.2 on 2025-05-06 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_orderdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='product_price',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderdetails', to='products.products'),
        ),
    ]
